# Generated by Django 6.0.1 on 2026-06-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('duracion_horas', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estudiantes', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
