# Generated by Django 6.0.1 on 2026-06-29 16:23

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.CreateModel(
            name='ActividadesDelCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_actividad', models.CharField(max_length=100)),
                ('descripcion_actividad', ckeditor.fields.RichTextField()),
                ('fecha_actividad', models.DateField(auto_now_add=True)),
                ('nombre_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Actividad del Curso',
                'verbose_name_plural': 'Actividades del Curso',
                'ordering': ['fecha_actividad'],
            },
        ),
    ]
