# Generated by Django 6.0.1 on 2026-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_options_actividadesdelcurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Convocatoria', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='actividadesdelcurso',
            name='fecha_actividad',
            field=models.DateField(),
        ),
    ]
