# Generated by Django 6.0.1 on 2026-06-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
